### PR TITLE
Added additional checks and tests for watson module

### PR DESCRIPTION
**Pull request by BryanCutler**

### CODE REVIEW

**Comment by BryanCutler** [comment]
build failure is 
```
======================================================================

FAIL: test_make_tokens_and_features (text_extensions_for_pandas.io.test_spacy.IOTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/CODAIT/text-extensions-for-pandas/text_extensions_for_pandas/io/test_spacy.py", line 71, in test_make_tokens_and_features

    (8, 8, [34, 35): '.', [34, 35): '.', '.', 'PUNCT', '.', 'punct', 1, '.', 'O', '', False, False, [0, 35): 'She sold c shills by the Sith Lord.')]"""

AssertionError: "[(0,[355 chars]N', 'det', 3, 'x', 'O', '',  True, False, [0, [970 chars].')]" != "[(0,[355 chars]N', 'compound', 3, 'x', 'O', '',  True, False,[975 chars].')]"

Diff is 1957 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
```
@frreiss is this a known failure?

**Comment by frreiss** [comment]
@BryanCutler The SpaCy language model keeps changing underneath our regression tests. Working on another temporary fix for now. We'll need to do some research to figure out a permanent fix.

**Comment by BryanCutler** [comment]
Thanks @frreiss , ok to merge this then?

**Comment by frreiss** [comment]
Yes, looks good to me otherwise. I've created #58 to fix the regression test failure. Hopefully for good this time.

**Pull request merged**
