### PR TITLE
added sentiment analysis use case

### PR DESCRIPTION
**Pull request by Monireh2**
New Notebook for Sentiment Analysis use case
=======
Pull request to add new notebook for sentiment analysis use case using Watson NLU, Text Extension for Pandas, Pandas and Scikit learn.

Change summary:
---------------
* Added new ipython notebook on the use case
* Added new Car Reviews dataset from Kaggle 

Signed-off-by: Monireh Ebrahimi <monireh@Monirehs-MacBook-Pro.local>

### CODE REVIEW

**Comment by Monireh2** [comment]
@frreiss @BryanCutler Please review!

**Comment by frreiss** [comment]
Looking good! Some comments inline via ReviewNB. There are two issues that really need to be cleared up before we can merge this:
* Fix the dataset issues (see https://github.com/CODAIT/text-extensions-for-pandas/pull/189#issuecomment-823447848). We can't have data with uncertain IP rights in our repository.
* Remove the really large output (see https://github.com/CODAIT/text-extensions-for-pandas/pull/189#issuecomment-823447866). It makes the notebook viewer freeze for a long time.

**Comment by frreiss** [comment]
Looks good to me.

**Review by frreiss — APPROVED** [review]

**Review by BryanCutler — COMMENTED** [review]
Apologies for the late review. Overall it looks great and a very nice use case for the Watson NLU component. Thanks for working on this @Monireh2 !

**Pull request merged**
